services:
  vllm:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    command: --model mlabonne/NeuralDaredevil-7B --dtype auto
    ipc: host

    # TODO: Remove after miner is dockerized
    network_mode: host
    ports:
      - 8000:8000
    volumes:
      - hf_cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  hf_cache:
